### ISSUE TITLE
Can I use this to add video editing capability to my unity app?

### ISSUE THREAD

**Issue by nsmith1024** [James231/Unity-Video-Editor-Template#4]
Hello,

Without downloading and installing this, i would like to know if it allows you to edit videos from within a unity app, or does it only work inside the unity editor itself?

Thanks

**Comment by James231** [comment]
Hi, it's for editing videos within the Unity Editor only. Not for editing videos in an app built with unity.

**Comment by nsmith1024** [comment]
Ok, when are you gonna add the ability to edit videos in an app built with unity??

**Comment by James231** [comment]
That's not the purpose of this project. I won't be adding it.
For that you're better off trying it yourself with Unity's [VideoPlayer](https://docs.unity3d.com/ScriptReference/Video.VideoPlayer.html) API, or maybe try the asset store.
